$schema: local.pipeline
name: iris_local_pipeline
version: 1

steps:
  - name: prep
    component: components/prep.yaml
    with:
      inputs: {}
      outputs:
        # on fige explicitement les chemins produits par prep
        out_dir: saves/temp        # passé au script via ${{outputs.out_dir}}
        csv: saves/temp/iris.csv      # pour rendu aux steps suivants
        meta: saves/temp/meta.json

  # - name: train
  #   component: components/train.yaml
  #   with:
  #     inputs:
  #       data_csv: ${{steps.prep.outputs.csv}}
  #     outputs:
  #       model_path: artifacts/model/model.joblib
  #       report_json: artifacts/model/report.json

  # - name: score
  #   component: components/score.yaml
  #   with:
  #     inputs:
  #       data_csv: ${{steps.prep.outputs.csv}}
  #       model_path: ${{steps.train.outputs.model_path}}
  #     outputs:
  #       metrics_path: artifacts/metrics/metrics.json
